# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 12:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0002_auto_20170913_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='links_links', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 12, 18, 53, 918758, tzinfo=utc)),
        ),
    ]
