# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 17:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20170913_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='list_title',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 17, 12, 11, 687228, tzinfo=utc)),
        ),
    ]
