# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 17:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20170913_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 17, 13, 36, 216254, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
